### ISSUE TITLE
Workflow status differ from status field

### ISSUE THREAD

**Issue by bm-stschneider** [gioboa/jira-plugin#27] opened 2018-11-12 07:38 UTC
Issue Type: <b>Bug</b>

It seems that the plugin cannot find my username although I'm logged in with that username and I have an issue in progress.
I even reassigned it to me with the plugin and it doesn't work.

Extension version: 0.9.1
VS Code version: Code - Insiders 1.29.0-insider (5f24c93878bd4bc645a4a17c620e2487b11005f9, 2018-11-10T00:26:25.769Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.03GB free)|
|Process Argv|-psn_0_9435391|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by gioboa** [comment] 2018-11-12 11:41
Hi @bm-stschneider ,
the problem is that your working issue list is empty?
The plugin search for issues assigned to you with status 'In progress' (status is configurable)
Here the Jira jql:
`${selected_project} AND status in (${statuses}) AND assignee in (currentUser()) ORDER BY status ASC, updated DESC`

**Comment by bm-stschneider** [comment] 2018-11-12 12:29
![image](https://user-images.githubusercontent.com/30625381/48347586-ee1dd380-e67e-11e8-86f2-4054e37cdb90.png)

**Comment by gioboa** [comment] 2018-11-12 12:36
It's a screenshot of Jira web application so I suppose it's not a VsCode plugin issue. :confused:

**Comment by bm-stschneider** [comment] 2018-11-12 12:37
Well, it would be nice if I could adjust the working issue status of the plugin

**Comment by gioboa** [comment] 2018-11-12 12:43
Now I understand. I take directly the status from Jira JSON response.I can check if there is some strange difference with some other status filed in the JSON.

**Comment by bm-stschneider** [comment] 2018-11-20 08:55
Ok I checked the REST call on status. And the name is 'In Progress' which schould be fine.
I also added it in the config 
![image](https://user-images.githubusercontent.com/30625381/48762015-5f2a4000-ecaa-11e8-86d6-818e00dc1e8c.png)
The ticket is under the Status: In Progress view for the active sprint also but when I filter by status it is not found and also is not found as working issue.

**Comment by gioboa** [comment] 2018-11-20 09:45
Try to search the ticket by id. 
When appear in the list you can also see the current status of the ticket. 
Is this In Progress?

**Comment by bm-stschneider** [comment] 2018-11-20 10:13
Yes, it is 'In Progress'

**Comment by bm-stschneider** [comment] 2018-11-20 10:29
I moved it into In Progress and reopened it again and checked the REST response and such. Yes I'm the assigne

**Comment by bm-stschneider** [comment] 2018-11-20 10:30
Tickets with other status are found.

**Comment by bm-stschneider** [comment] 2018-11-20 10:52
Even if I add other status to the working issue status that I can filter by status successfully, it doesn't work

**Comment by bm-stschneider** [comment] 2018-11-20 10:54
the working issue works with the other status but the explorer filter does not.

**Comment by gioboa** [comment] 2018-11-20 11:09
I lost a little bit the focus of the problem. 😕 
All tickets with `In problem` status have this issue?

**Comment by gioboa** [comment] 2018-11-20 11:34
When you filter by status from explorer the plugin perform this query:
`project = ${project} AND status = '${status}' ORDER BY status ASC, updated DESC`
From working issue in the status bar exec this query:
`project = ${project} AND status in (${statuses}) AND assignee in (currentUser()) ORDER BY status ASC, updated DESC`
where ${statuses} is taken from `workingIssueStatues` setting 
Please try to perform this JQL to Jira web application to understand the origin of the issue. 
Thanks. 👍

**Comment by bm-stschneider** [comment] 2018-11-20 12:02
Ok so the statuses from the api are not resolved correctly as it seems. The Status that should be 'In Arbeit' is also shown as "In Progress" but they do not match the status then.

**Comment by gioboa** [comment] 2018-11-20 12:19
Nice catch. :smile: 
Yes, I can add something like this. :+1:

**Comment by gioboa** [comment] 2018-11-22 08:38
@bm-stschneider  Hi,
in the v 0.10.4 I added a [new setting](https://github.com/gioboa/jira-plugin/blob/68a464bdef865110f428b32ccd1c72003d38abd0/package.json#L95) to solve this kind of problem.
It's a workaround for your issue.
Let me know. Thanks. 👍

**Comment by bm-stschneider** [comment] 2018-11-22 11:12
Wonderful 👍

**Comment by gioboa** [comment] 2018-11-22 11:12
Can I close the issue?

**Closed** 2018-11-22 11:12 UTC
Labels: feature-request
